//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triamun.Log4NetViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Triamun.Log4NetViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty....
        /// </summary>
        internal static string AutoLogFileMenuEmpty {
            get {
                return ResourceManager.GetString("AutoLogFileMenuEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string AutoLogFileMenuLoading {
            get {
                return ResourceManager.GetString("AutoLogFileMenuLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseLog {
            get {
                object obj = ResourceManager.GetObject("CloseLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataSourceError {
            get {
                object obj = ResourceManager.GetObject("DataSourceError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application registration.
        /// </summary>
        internal static string DlgTitle_Registration {
            get {
                return ResourceManager.GetString("DlgTitle_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditConfig {
            get {
                object obj = ResourceManager.GetObject("EditConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply the filter..
        /// </summary>
        internal static string Err_FailedToApplyFilter {
            get {
                return ResourceManager.GetString("Err_FailedToApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to undo the configuration changes..
        /// </summary>
        internal static string Err_FailedToCancelConfigChanges {
            get {
                return ResourceManager.GetString("Err_FailedToCancelConfigChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear the recently opened logs..
        /// </summary>
        internal static string Err_FailedToClearRecent {
            get {
                return ResourceManager.GetString("Err_FailedToClearRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close the log..
        /// </summary>
        internal static string Err_FailedToCloseLog {
            get {
                return ResourceManager.GetString("Err_FailedToCloseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to edit the settings..
        /// </summary>
        internal static string Err_FailedToEditSettings {
            get {
                return ResourceManager.GetString("Err_FailedToEditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to go to a specific event..
        /// </summary>
        internal static string Err_FailedToGoToSpecificEvent {
            get {
                return ResourceManager.GetString("Err_FailedToGoToSpecificEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the detailled view of the value..
        /// </summary>
        internal static string Err_FailedToOpenDetailView {
            get {
                return ResourceManager.GetString("Err_FailedToOpenDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the log..
        /// </summary>
        internal static string Err_FailedToOpenLog {
            get {
                return ResourceManager.GetString("Err_FailedToOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the recent log..
        /// </summary>
        internal static string Err_FailedToOpenRecentLog {
            get {
                return ResourceManager.GetString("Err_FailedToOpenRecentLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rebuild the recent logs menu..
        /// </summary>
        internal static string Err_FailedToRebuildRecentMenu {
            get {
                return ResourceManager.GetString("Err_FailedToRebuildRecentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh the logs..
        /// </summary>
        internal static string Err_FailedToRefresh {
            get {
                return ResourceManager.GetString("Err_FailedToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset the filter..
        /// </summary>
        internal static string Err_FailedToResetFilter {
            get {
                return ResourceManager.GetString("Err_FailedToResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the configuration..
        /// </summary>
        internal static string Err_FailedToSaveConfig {
            get {
                return ResourceManager.GetString("Err_FailedToSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the filter on or off..
        /// </summary>
        internal static string Err_FailedToToggleFilterEnabled {
            get {
                return ResourceManager.GetString("Err_FailedToToggleFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the follow last log mode on or off..
        /// </summary>
        internal static string Err_FailedToToggleFollowLastLog {
            get {
                return ResourceManager.GetString("Err_FailedToToggleFollowLastLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the pause mode on or off..
        /// </summary>
        internal static string Err_FailedToTogglePause {
            get {
                return ResourceManager.GetString("Err_FailedToTogglePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to udpate the state of the controls..
        /// </summary>
        internal static string Err_FailedToUpdateControlsState {
            get {
                return ResourceManager.GetString("Err_FailedToUpdateControlsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error at startup.
        /// </summary>
        internal static string Err_FatalStartup {
            get {
                return ResourceManager.GetString("Err_FatalStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register the current application to open the &quot;.log4net&quot; files..
        /// </summary>
        internal static string Err_RegistationError {
            get {
                return ResourceManager.GetString("Err_RegistationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterApply {
            get {
                object obj = ResourceManager.GetObject("FilterApply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterEnabled {
            get {
                object obj = ResourceManager.GetObject("FilterEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterErase {
            get {
                object obj = ResourceManager.GetObject("FilterErase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading: {0} events loaded..
        /// </summary>
        internal static string Fmt_LoadingEvents {
            get {
                return ResourceManager.GetString("Fmt_LoadingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown events: {0}.
        /// </summary>
        internal static string Fmt_ShownEvents {
            get {
                return ResourceManager.GetString("Fmt_ShownEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total events: {0}.
        /// </summary>
        internal static string Fmt_TotalEvents {
            get {
                return ResourceManager.GetString("Fmt_TotalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FollowLastLog {
            get {
                object obj = ResourceManager.GetObject("FollowLastLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToLog {
            get {
                object obj = ResourceManager.GetObject("GoToLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogSourceFile {
            get {
                object obj = ResourceManager.GetObject("LogSourceFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogSourceTelnet {
            get {
                object obj = ResourceManager.GetObject("LogSourceTelnet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the recently opened logs..
        /// </summary>
        internal static string Msg_ClearRecentConfirm {
            get {
                return ResourceManager.GetString("Msg_ClearRecentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recently opened logs..
        /// </summary>
        internal static string Msg_ClearRecentConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_ClearRecentConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event number {0} could not be found..
        /// </summary>
        internal static string Msg_GoToEventNotFound {
            get {
                return ResourceManager.GetString("Msg_GoToEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        internal static string Msg_GoToEventNotFoundTitle {
            get {
                return ResourceManager.GetString("Msg_GoToEventNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current application is not registered as default application to open the log files with the extension &quot;{0}&quot;.
        ///
        ///Would you like to register the application to open these files ?.
        /// </summary>
        internal static string Msg_RegisterFileExtension {
            get {
                return ResourceManager.GetString("Msg_RegisterFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension registration..
        /// </summary>
        internal static string Msg_RegisterFileExtensionTitle {
            get {
                return ResourceManager.GetString("Msg_RegisterFileExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current application was successfully registered to open the &quot;.log4net&quot; files..
        /// </summary>
        internal static string Msg_RegistrationSuccess {
            get {
                return ResourceManager.GetString("Msg_RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Online {
            get {
                object obj = ResourceManager.GetObject("Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenLog {
            get {
                object obj = ResourceManager.GetObject("OpenLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseCapture {
            get {
                object obj = ResourceManager.GetObject("PauseCapture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Status_Offline {
            get {
                return ResourceManager.GetString("Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Status_Online {
            get {
                return ResourceManager.GetString("Status_Online", resourceCulture);
            }
        }
    }
}
